<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class PointsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
       DB::table('points')->truncate();
       DB::table('points')->insert([
           [
               'tournament_id' => 2,
               'group_id' => 1,
               'round_id' => 2,
               'team_id' => 1,
               'matches_played' => 5,
               'wins' => 3,
               'losses' => 2,
               'matches_not_played' => 0,
               'matches_tied' => 0,
               'net_run_rate' => 1.50,
               'total_points' => 9,
               'created_at' => now(),
               'updated_at' => now(),
               'deleted_at' => null,
           ],
           [
               'tournament_id' => 2,
               'group_id' => 2,
               'round_id' => 2,
               'team_id' => 2,
               'matches_played' => 5,
               'wins' => 2,
               'losses' => 3,
               'matches_not_played' => 0,
               'matches_tied' => 0,
               'net_run_rate' => 0.20,
               'total_points' => 4,
               'created_at' => now(),
               'updated_at' => now(),
               'deleted_at' => null,
           ],
           [
               'tournament_id' => 2,
               'group_id' => 3,
               'round_id' => 2,
               'team_id' => 3,
               'matches_played' => 5,
               'wins' => 4,
               'losses' => 1,
               'matches_not_played' => 0,
               'matches_tied' => 0,
               'net_run_rate' => 2.00,
               'total_points' => 12,
               'created_at' => now(),
               'updated_at' => now(),
               'deleted_at' => null,
           ],
           [
               'tournament_id' => 2,
               'group_id' => 4,
               'round_id' => 2,
               'team_id' => 4,
               'matches_played' => 5,
               'wins' => 1,
               'losses' => 4,
               'matches_not_played' => 0,
               'matches_tied' => 0,
               'net_run_rate' => -0.50,
               'total_points' => 2,
               'created_at' => now(),
               'updated_at' => now(),
               'deleted_at' => null,
           ],
           [
               'tournament_id' => 2,
               'group_id' => 5,
               'round_id' => 2,
               'team_id' => 5,
               'matches_played' => 5,
               'wins' => 3,
               'losses' => 2,
               'matches_not_played' => 0,
               'matches_tied' => 0,
               'net_run_rate' => 1.00,
               'total_points' => 9,
               'created_at' => now(),
               'updated_at' => now(),
               'deleted_at' => null,
           ],
           [
               'tournament_id' => 2,
               'group_id' => 6,
               'round_id' => 2,
               'team_id' => 6,
               'matches_played' => 5,
               'wins' => 4,
               'losses' => 1,
               'matches_not_played' => 0,
               'matches_tied' => 0,
               'net_run_rate' => 3.00,
               'total_points' => 12,
               'created_at' => now(),
               'updated_at' => now(),
               'deleted_at' => null,
           ],
           [
               'tournament_id' => 2,
               'group_id' => 7,
               'round_id' => 2,
               'team_id' => 7,
               'matches_played' => 5,
               'wins' => 2,
               'losses' => 3,
               'matches_not_played' => 0,
               'matches_tied' => 0,
               'net_run_rate' => 0.10,
               'total_points' => 4,
               'created_at' => now(),
               'updated_at' => now(),
               'deleted_at' => null,
           ],           
           [
            'tournament_id' => 3,
            'group_id' => 8,
            'round_id' => 3,
            'team_id' => 1,
            'matches_played' => 5,
            'wins' => 3,
            'losses' => 2,
            'matches_not_played' => 0,
            'matches_tied' => 0,
            'net_run_rate' => 1.50,
            'total_points' => 9,
            'created_at' => now(),
            'updated_at' => now(),
            'deleted_at' => null,
        ],
        [
            'tournament_id' => 3,
            'group_id' => 8,
            'round_id' => 3,
            'team_id' => 2,
            'matches_played' => 5,
            'wins' => 2,
            'losses' => 3,
            'matches_not_played' => 0,
            'matches_tied' => 0,
            'net_run_rate' => 0.20,
            'total_points' => 4,
            'created_at' => now(),
            'updated_at' => now(),
            'deleted_at' => null,
        ],
        [
            'tournament_id' => 3,
            'group_id' => 9,
            'round_id' => 3,
            'team_id' => 3,
            'matches_played' => 5,
            'wins' => 4,
            'losses' => 1,
            'matches_not_played' => 0,
            'matches_tied' => 0,
            'net_run_rate' => 2.00,
            'total_points' => 12,
            'created_at' => now(),
            'updated_at' => now(),
            'deleted_at' => null,
        ],
        [
            'tournament_id' => 3,
            'group_id' => 9,
            'round_id' => 3,
            'team_id' => 4,
            'matches_played' => 5,
            'wins' => 1,
            'losses' => 4,
            'matches_not_played' => 0,
            'matches_tied' => 0,
            'net_run_rate' => -0.50,
            'total_points' => 2,
            'created_at' => now(),
            'updated_at' => now(),
            'deleted_at' => null,
        ],
        [
            'tournament_id' => 3,
            'group_id' => 10,
            'round_id' => 3,
            'team_id' => 5,
            'matches_played' => 5,
            'wins' => 3,
            'losses' => 2,
            'matches_not_played' => 0,
            'matches_tied' => 0,
            'net_run_rate' => 1.00,
            'total_points' => 9,
            'created_at' => now(),
            'updated_at' => now(),
            'deleted_at' => null,
        ],
        [
            'tournament_id' => 3,
            'group_id' => 10,
            'round_id' => 3,
            'team_id' => 6,
            'matches_played' => 5,
            'wins' => 4,
            'losses' => 1,
            'matches_not_played' => 0,
            'matches_tied' => 0,
            'net_run_rate' => 3.00,
            'total_points' => 12,
            'created_at' => now(),
            'updated_at' => now(),
            'deleted_at' => null,
        ],
        [
            'tournament_id' => 3,
            'group_id' => 11,
            'round_id' => 3,
            'team_id' => 7,
            'matches_played' => 5,
            'wins' => 2,
            'losses' => 3,
            'matches_not_played' => 0,
            'matches_tied' => 0,
            'net_run_rate' => 0.10,
            'total_points' => 4,
            'created_at' => now(),
            'updated_at' => now(),
            'deleted_at' => null,
        ],
                   [
            'tournament_id' => 4,
            'group_id' => 8,
            'round_id' => 4,
            'team_id' => 1,
            'matches_played' => 5,
            'wins' => 3,
            'losses' => 2,
            'matches_not_played' => 0,
            'matches_tied' => 0,
            'net_run_rate' => 1.50,
            'total_points' => 9,
            'created_at' => now(),
            'updated_at' => now(),
            'deleted_at' => null,
        ],
        [
            'tournament_id' => 4,
            'group_id' => 8,
            'round_id' => 4,
            'team_id' => 2,
            'matches_played' => 5,
            'wins' => 2,
            'losses' => 3,
            'matches_not_played' => 0,
            'matches_tied' => 0,
            'net_run_rate' => 0.20,
            'total_points' => 4,
            'created_at' => now(),
            'updated_at' => now(),
            'deleted_at' => null,
        ],
        [
            'tournament_id' => 4,
            'group_id' => 9,
            'round_id' => 4,
            'team_id' => 3,
            'matches_played' => 5,
            'wins' => 4,
            'losses' => 1,
            'matches_not_played' => 0,
            'matches_tied' => 0,
            'net_run_rate' => 2.00,
            'total_points' => 12,
            'created_at' => now(),
            'updated_at' => now(),
            'deleted_at' => null,
        ],
        [
            'tournament_id' => 4,
            'group_id' => 9,
            'round_id' => 4,
            'team_id' => 4,
            'matches_played' => 5,
            'wins' => 1,
            'losses' => 4,
            'matches_not_played' => 0,
            'matches_tied' => 0,
            'net_run_rate' => -0.50,
            'total_points' => 2,
            'created_at' => now(),
            'updated_at' => now(),
            'deleted_at' => null,
        ],
        [
            'tournament_id' => 4,
            'group_id' => 10,
            'round_id' => 4,
            'team_id' => 5,
            'matches_played' => 5,
            'wins' => 3,
            'losses' => 2,
            'matches_not_played' => 0,
            'matches_tied' => 0,
            'net_run_rate' => 1.00,
            'total_points' => 9,
            'created_at' => now(),
            'updated_at' => now(),
            'deleted_at' => null,
        ],
        [
            'tournament_id' => 4,
            'group_id' => 10,
            'round_id' => 4,
            'team_id' => 6,
            'matches_played' => 5,
            'wins' => 4,
            'losses' => 1,
            'matches_not_played' => 0,
            'matches_tied' => 0,
            'net_run_rate' => 3.00,
            'total_points' => 12,
            'created_at' => now(),
            'updated_at' => now(),
            'deleted_at' => null,
        ],
        [
            'tournament_id' => 4,
            'group_id' => 11,
            'round_id' => 4,
            'team_id' => 7,
            'matches_played' => 5,
            'wins' => 2,
            'losses' => 3,
            'matches_not_played' => 0,
            'matches_tied' => 0,
            'net_run_rate' => 0.10,
            'total_points' => 4,
            'created_at' => now(),
            'updated_at' => now(),
            'deleted_at' => null,
        ],
       ]);
   }
}
