<?php
return [
    '0' => [
        "No run there. @striker_name was looking to play it safe. That’s a dot ball.",
        "No run there. It’s a good length delivery, right on the off stump.",
    ],
    '1' => [
         "He’s quick off the mark! @striker_name takes off for a single.",
         "And there it is—just a single. Good running between the wickets!",
         "Smart cricket from @striker_name, rotating the strike and keeping the scoreboard ticking.",
         "He’s quick to run! @striker_name sprints for the single, and it looks like he’ll make it easily.",
         "There it is—one run added to the total. Good running, keeping the pressure on the fielders.",
         "Every run counts, especially in a tight match like this!",
         "@striker_name runs hard and makes it easily. Just a single on the board.",
    ],
    '2' => [
        "Two runs added to the score. Excellent running and great shot placement by @striker_name!",
        "Two more runs on the board—good awareness from @striker_name to exploit the gap.",
        "Great running between the wickets! They complete the second run comfortably.",
        "Two runs added to the total. That’s excellent running!",
        "That’s two runs added to the score! Smart running and a well-placed shot.",
        "They make it! Three runs added to the total. Fantastic running and a great shot by Kohli!",
    ],
    '3' => [
         "And there it is! @striker_name and the non-striker complete three runs.",
         "That was fantastic running between the wickets. @striker_name really pushed hard!",
         "Great awareness to take that third run, especially with the ball still in play.",
         "The crowd loves it! Three more runs on the board, and @striker_name’s looking in great form."
    ],
    '4' => [
        "And that’s four runs! @striker_name has found the gap beautifully.",
        "The timing was immaculate, and the ball raced away to the boundary.",
        "The crowd erupts! @striker_name is in full flow now, and that’s a vital boundary.",
        "Four runs added to the total, and the pressure is mounting on the bowlers.",
        "Four runs! @striker_name has struck that beautifully!",
        "That’s a fantastic boundary, adding vital runs to the scoreboard.",
    ],
    '6' => [
        "And that’s six runs! What a massive hit from @striker_name!",
        "Six runs added to the total, and the momentum is shifting!",
        "That’s six runs! @striker_name has launched that one into the stands!",
        "What a shot! @striker_name timed it perfectly, sending it sailing over the boundary.",
        "@striker_name is in sensational form, and that six adds significant pressure on the bowlers.",
        "A magnificent strike, and that’s six more runs added to the total!"
    ],
        'NB' => [
        "Oh, that's a no-ball from @bowler_name! @striker_name on strike gets a free hit, and @non_striker_name at the non-striker’s end looks thrilled with this bonus opportunity!",
        "It's a no-ball! @striker_name stands ready on strike, while @non_striker_name at the non-striker’s end smiles—this could be a big moment for them!",
        "No ball called by the umpire! @striker_name on strike gets a free hit, and @non_striker_name at the other end is already preparing for a quick single.",
        "What a mistake—no ball by @bowler_name! @striker_name will have a free hit now, with @non_striker_name watching closely from the non-striker’s end.",
        "And that's a no-ball! The crowd roars as @striker_name gets a free hit, with @non_striker_name standing ready for a possible second run!"
    ],
    'nb+w' => [
        "It's a no-ball, and a run out!",
        "No-ball called! @striker_name gets another chance, but @non_striker_name at the non-striker’s end is run out trying to steal an extra run.",
        "The umpire signals no-ball, and what drama! @striker_name survives on strike, but @non_striker_name at the non-striker’s end is run out after a mix-up!",
        "What an event—no-ball from @bowler_name, but @striker_name is safe! @non_striker_name at the non-striker’s end, however, is run out in the scramble."

    ],
    'WD' => [
        "Wide ball from @bowler_name! @striker_name on strike lets it go, and @non_striker_name at the non-striker’s end looks eager to capitalize on any extras.",
        "It’s a wide! @bowler_name misses his line, and @striker_name on strike watches it sail by, with @non_striker_name looking ready at the other end.",
        "Oh, that’s a wide from @bowler_name! @striker_name on strike wisely leaves it, while @non_striker_name signals for a quick extra at the non-striker’s end.",
        "Wide ball called! @bowler_name strays too far off, and @striker_name on strike watches it go, with @non_striker_name nodding in approval at the other end.",
        "Wide from @bowler_name! @striker_name lets it go easily, and @non_striker_name at the non-striker’s end signals for the bonus run with a grin.",
    ],  
    'wd+w' => [
        "It’s a wide! But wait, @striker_name's tried to steal a run and has been run out—@non_striker_name at the non-striker's end watches as the wicket falls unexpectedly!",
        "Wide ball from @bowler_name, but @striker_name’s been stumped trying to advance! @non_striker_name at the non-striker’s end looks stunned by the quick turn of events!",
        "Oh, that's a wide from Rashid! Williamson tried to sneak a single and was caught short—Conway at the other end is left in disbelief!",
        "It's a wide down leg side, but @striker_name is caught out trying to flick it! @non_striker_name at the non-striker’s end can't believe it—they lose a wicket on a wide!",
        "Wide ball from @bowler_name! @striker_name gets stumped reaching for it, with @non_striker_name at the other end looking frustrated as a wicket falls off a wide!",
    ],
    'caught' => [
        "It’s a big wicket! @striker_name goes for the big shot but is caught at long-on! @non_striker_name at the non-striker’s end can only watch as the opener departs.",
        "What a catch! @striker_name tries to clear the infield but is taken at cover! @non_striker_name at the non-striker’s end looks disappointed as they lose another wicket.",
        "Oh, he’s out! @striker_name goes for the pull but finds the fielder in the deep! @non_striker_name at the other end is left stranded as the fielding side celebrates.",
        "That’s out! @striker_name slices it high and is caught at point! @non_striker_name at the non-striker’s end watches on as his partner heads back to the pavilion.",
        "Incredible catch! @striker_name tries to go over midwicket but is caught! @non_striker_name, at the non-striker’s end, looks on as their team loses a key wicket.",
    ],
    'b+w' => [
        "Missed by @striker_name! The ball rolls to the keeper, and @non_striker_name at the non-striker’s end is run out trying for a quick bye—what a disaster!",
        "What just happened? @striker_name swings and misses, but @non_striker_name takes a risky run and is run out by a sharp throw from the keeper!",
        "A complete mix-up! @striker_name misses the ball, and @non_striker_name at the non-striker’s end is caught short going for a bye—out of nowhere, the fielding side strikes!",
        "Big trouble for Rizwan and Babar! Rizwan misses the shot, and the keeper’s quick throw catches Babar short of his crease while stealing a bye!",
        "Oh, that's poor running! @striker_name misses the ball completely, but @non_striker_name charges down and is run out trying for a cheeky bye!",
    ],
    'B' => [
        "@striker_name misses the flick, but the ball sneaks past the keeper, and @non_striker_name at the non-striker’s end calls for a quick bye—sharp running by the pair!",
        "@striker_name lets it go, and the ball races past the keeper! @non_striker_name at the non-striker’s end is quick to dash through for a single bye.",
        "What happened there? @striker_name misses the shot, but @non_striker_name at the non-striker’s end reacts swiftly as they steal a bye!",
        "@striker_name misjudges the delivery, but @striker_name at the non-striker’s end spots the chance, and they pick up a cheeky bye!",
        "@striker_name misses the cut, but the ball @striker_name off the keeper, allowing @non_striker_name at the non-striker’s end to nab a sneaky bye!",
    ],
    'EXTRA_RUNS' => [
        "Brilliant running between the wickets! @striker_name and @non_striker_name take on the fielders, and they make it home for a brilliant @extran_runs-run chase!",
        "What a shot! @striker_name drives it to the boundary, and they come back for an excellent @extra_runs-run hustle, with @non_striker_name at the non-striker’s end pushing hard.",
        "That’s excellent running from Babar and Rizwan! They’ve taken @extra_runs runs with a couple of well-timed pushes and quick turns!",
        "What a turn of events! @striker_name and @non_striker_name complete a stunning @extra_runs runs with sheer running, putting pressure on the fielders at the non-striker’s end.",
        "Fantastic running between the wickets! @striker_name and @non_striker_name have managed to grab @extra_runs runs, and they're back for a sixth—great teamwork!",
    ],
    'W' => [
        "Clean bowled! @striker_name misses the line completely, and the stumps are rattled while @non_striker_name at the non-striker’s end can only watch in disbelief!",
        "What a delivery! Warner is beaten all ends up, and the stumps are shattered, leaving @non_striker_name stranded at the other end!",
        "Through the gate! @bowler_name is bowled, and @non_striker_name at the non-striker’s end looks stunned by that peach of a delivery!",
        "Knocked him over! @striker_name departs as the ball crashes into his stumps, with @non_striker_name at the non-striker’s end shaking his head in frustration.",
        "Absolute beauty! @bowler_name is bowled, and @non_striker_name at the other end can only admire the bowler’s precision.",
        "Oh, that's a sensational throw! @striker_name on strike is run out, with Stokes at the non-striker’s end left stranded!",
        "What a brilliant piece of fielding! @striker_name Gill is run out after a direct hit, with @non_striker_name at the non-striker’s end unable to get back in time!",
        "It’s a run-out! @striker_name is sent packing after a sharp piece of fielding, with @non_striker_name at the non-striker’s end just a step too late!",
        "Unbelievable! @striker_name is run out by a brilliant direct hit, and @non_striker_name at the non-striker’s end is left helpless!",
        "Oh, what a disaster for the batting side! @striker_name on strike is run out, with @non_striker_name at the non-striker’s end caught out of his ground!",
    ],
    'bowled' => [
        "Clean bowled! @striker_name misses the line completely, and the stumps are rattled while @non_striker_name at the non-striker’s end can only watch in disbelief!",
        "What a delivery! Warner is beaten all ends up, and the stumps are shattered, leaving @non_striker_name stranded at the other end!",
        "Through the gate! @bowler_name is bowled, and @non_striker_name at the non-striker’s end looks stunned by that peach of a delivery!",
        "Knocked him over! @striker_name departs as the ball crashes into his stumps, with @non_striker_name at the non-striker’s end shaking his head in frustration.",
        "Absolute beauty! @bowler_name is bowled, and @non_striker_name at the other end can only admire the bowler’s precision.",
        "Oh, that's a sensational throw! @striker_name on strike is run out, with Stokes at the non-striker’s end left stranded!",
        "What a brilliant piece of fielding! @striker_name Gill is run out after a direct hit, with @non_striker_name at the non-striker’s end unable to get back in time!",
        "It’s a run-out! @striker_name is sent packing after a sharp piece of fielding, with @non_striker_name at the non-striker’s end just a step too late!",
        "Unbelievable! @striker_name is run out by a brilliant direct hit, and @non_striker_name at the non-striker’s end is left helpless!",
        "Oh, what a disaster for the batting side! @striker_name on strike is run out, with @non_striker_name at the non-striker’s end caught out of his ground!",
    ],
    'runout' => [
        "Fantastic work by @bowler_name! @striker_name attempted a quick single, but @non_striker_name was caught short of the crease. It's a run-out!",
        "A direct hit from @bowler_name! @striker_name and @non_striker_name went for a risky second run, but @non_striker_name couldn't make it back in time.",
        "Superb throw by @bowler_name! @striker_name pushed for a quick single, but @non_striker_name was left stranded. Run-out!",
        "Sharp fielding by @bowler_name! @striker_name and @non_striker_name misjudged the run, and @non_striker_name pays the price. Out!",
        "A brilliant piece of fielding by @bowler_name! The striker, @striker_name, set off for a risky run, but the non-striker, @non_striker_name, was caught short of the crease. It's a run-out!"
    ],
    'retired hurt' => [
        "@striker_name looks in discomfort and has decided to retire hurt. Hope it's not too serious.",
        "Bad luck for @striker_name, who is forced to leave the field retired hurt due to an injury.",
        "@striker_name retires hurt after sustaining an injury. The team will hope for a quick recovery.",
        "It's unfortunate! @striker_name has to walk off retired hurt. A setback for the team.",
        "@striker_name is leaving the crease retired hurt. The physios are attending to them.",
        "Oh no! @striker_name seems unable to continue and retires hurt. Fingers crossed for a quick recovery.",
    ],
    'retiredout' => [
        "@striker_name has retired out, a tactical decision by the team.",
        "Unusual! @striker_name retires out, handing the opportunity to the next batter.",
        "A rare sight as @striker_name retires out, perhaps for strategic reasons.",
        "@striker_name steps away from the crease, retiring out. A calculated move by the team.",
        "Interesting strategy! @striker_name has been retired out to bring in a fresh batter.",
        "Surprising! @striker_name walks off retiring out, potentially as part of the team's plan.",
    ],
    'caught behind' => [
        "Edged and taken by @bowler_name! @striker_name couldn't keep it out of the keeper's gloves.",
        "A faint edge, and @bowler_name makes no mistake! @striker_name is out caught behind.",
        "What a grab by @bowler_name! @striker_name nicked it, and the keeper does the rest.",
        "Sharp work by @bowler_name! @striker_name edges it, and it's out.",
        "Great keeping by @bowler_name! @striker_name tried to defend but got the edge.",
    ],
    'caught & bowled' => [
        "@striker_name edges it, and @bowler_name takes the simplest of catches behind the stumps!",
        "Caught behind! @bowler_name makes no mistake as @striker_name is dismissed.",
        "Brilliant reflexes by @bowler_name! @striker_name is out caught and behind.",
        "A feather touch from @striker_name, and @bowler_name grabs it behind! Out!",
        "Sharp work by @bowler_name behind the stumps! @striker_name has to go, caught and behind.",
    ],
    'hit wicket' => [
        "Oh no! @striker_name has hit the stumps with the bat! @bowler_name gets the wicket in a bizarre fashion.",
        "A rare dismissal! @striker_name steps back and disturbs the stumps. Hit wicket for @bowler_name!",
        "Unbelievable! @striker_name loses balance and hits the stumps. @bowler_name claims the wicket!",
        "@striker_name is out hit wicket! A moment of misfortune gives @bowler_name another wicket.",
        "Drama at the crease! @striker_name accidentally hits the stumps, and @bowler_name gets the credit.",
    ],
    'stumped' => [
        "Quick work by @bowler_name! @striker_name stepped out, but the keeper did the rest. Stumped!",
        "Brilliant bowling by @bowler_name! @striker_name was beaten and stumped in a flash.",
        "Superb stumping off @bowler_name's delivery! @striker_name was left stranded outside the crease.",
        "Clever from @bowler_name! @striker_name dances down the pitch but can't make it back. Stumped!",
        "What a delivery by @bowler_name! @striker_name is out stumped after being lured out of the crease.",
    ],
    'run out (mankaded)' => [
        "@bowler_name catches @non_striker_name backing up too far! It's a run out (Mankaded).",
        "Smart thinking by @bowler_name! @non_striker_name is run out for leaving the crease early.",
        "Controversial moment! @bowler_name stops mid-delivery and runs out @non_striker_name at the non-striker's end.",
        "Alert work by @bowler_name! @non_striker_name is caught out of the crease and run out (Mankaded).",
        "Game awareness from @bowler_name! @non_striker_name is run out for not staying inside the crease.",
    ],
];